version: "3.9"

services:
  db:
    image: postgres:16
    container_name: flowsight-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: flowsight
      POSTGRES_PASSWORD: flowsight
      POSTGRES_DB: nuh_staging
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
