[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flowsight"
version = "0.1.0"
description = "NHS analytics PoC"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]          # <-- tells setuptools your code is in /src